export const CHARACTERES_FETCH_SUCCEEDED = 'CHARACTERES_FETCH_SUCCEEDED'
export const CHARACTERES_FETCH_REQUESTED = 'CHARACTERES_FETCH_REQUESTED'

export const CHARACTER_FETCH_SUCCEEDED = 'CHARACTER_FETCH_SUCCEEDED'
export const CHARACTER_FETCH_REQUESTED = 'CHARACTER_FETCH_REQUESTED'

export const SET_LANGUAGE = 'SET_LANGUAGE'